[package]
name = "clipman"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust="4.8.0"
mki="0.2.3"
clipboard-win="4.5.0"
serde_yaml="0.9.17"
serde = {version="1.0", features = ["derive"]}